### ISSUE TITLE
app chart cron job name length is more than 52 chars

### ISSUE THREAD

**Issue by bsushmith** [odpf/charts#73]
**Description**
cron job names from app chart have a length of more than 52 characters, causing the deployment to fail.

Line - https://github.com/odpf/charts/blob/main/stable/app/templates/cron.yaml#L9

Need to reduce the length to `<=` 52 characters.
Like -  ```name: "{{ $fullName | trunc 24 }}-{{ $i }}-{{ $job.name | trunc 24}}"```

**Comment by rohilsurana** [comment]
Is this a default kubernetes limitation? Can you add a doc reference as well?

**Comment by bsushmith** [comment]
As per the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#:~:text=The%20name%20must%20be%20no,no%20more%20than%2063%20characters)

```The name must be no longer than 52 characters. This is because the CronJob controller will automatically append 11 characters to the job name provided and there is a constraint that the maximum length of a Job name is no more than 63 characters```
